[build]
builder = "NIXPACKS"

[build.nixpacksCommands]
before = "pip install -r requirements.txt"
build = "python manage.py collectstatic --no-input"
after = "python manage.py migrate --no-input"

[deploy]
startCommand = "gunicorn config.wsgi --log-file -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
